version: "3"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.10"
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
